//! The authority boundary for public research. External content is always data.

pub mod api;
#[cfg(feature = "service")]
pub mod archive;
pub mod bridge;
#[cfg(feature = "service")]
pub mod browser;
#[cfg(feature = "service")]
pub mod budget;
#[cfg(feature = "service")]
pub mod cache;
pub mod config;
#[cfg(feature = "service")]
pub mod diagnostics;
#[cfg(feature = "service")]
pub mod egress;
#[cfg(feature = "service")]
pub mod egress_control;
pub mod error;
#[cfg(feature = "service")]
pub mod fetch;
#[cfg(feature = "service")]
pub mod http;
pub mod mcp;
pub mod policy;
pub mod protocol;
#[cfg(feature = "service")]
pub mod provider;
#[cfg(feature = "service")]
pub mod reports;
#[cfg(feature = "service")]
pub mod robots;
#[cfg(feature = "service")]
pub mod rpc;
#[cfg(feature = "service")]
pub mod service;
#[cfg(feature = "service")]
pub mod socket;
#[cfg(feature = "service")]
pub mod store;
#[cfg(feature = "service")]
pub mod vpn_observer;
#[cfg(feature = "service")]
pub mod worker;
